name: Hello World CI/CD

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from CI/CD Pipeline 🚀"

      - name: Build
        run: echo "Building application..."

      - name: Test
        run: echo "Running tests..."

      - name: Deploy
        run: echo "Deploying application..."
